# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IakjLSYwlMz4kQx1xfPWCqOsSiXyHmNV
"""

from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from google.colab import files
files.upload()
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d nguyentrongdai/vietnamese-currency
!unzip vietnamese-currency.zip -d vietnamese-currency_data

from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os

data_dir = 'vietnamese-currency_data/dataset'
train_datagen = ImageDataGenerator(rescale = 1 / 255.0,
                                   validation_split = 0.2,
                                   rotation_range = 20,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
train_generator = train_datagen.flow_from_directory(
    data_dir,
    target_size = (128, 128),
    batch_size =32,
    class_mode = 'categorical',
    subset = 'training')

validation_generator = train_datagen.flow_from_directory(
    data_dir,
    target_size = (128, 128),
    batch_size = 32,
    class_mode = 'categorical',
    subset = 'validation')

from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten, Dropout
from keras.models import Sequential
model=Sequential()
model.add(Conv2D(32, (3,3),activation='relu',input_shape=(128,128,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(64, (3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Conv2D(128, (3,3),activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(12,activation='softmax'))
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

model.fit(train_generator,epochs=5,validation_data=validation_generator)

model.save('final_model.h5')

from google.colab import files
import cv2
import numpy as np
import matplotlib.pyplot as plt

uploaded = files.upload()
img_path = list(uploaded.keys())[0]
img = cv2.imread(img_path)                   # đọc ảnh màu
img_resized = cv2.resize(img, (128,128))     # resize
img_array = img_resized / 255.0              # chuẩn hóa (0-1)
img_array = np.expand_dims(img_array, axis=0) # thêm chiều batch
pred = model.predict(img_array)
class_index = np.argmax(pred)   # lấy nhãn có xác suất cao nhất
confidence = np.max(pred)
labels = list(train_generator.class_indices.keys())
print("Dự đoán:", labels[class_index], "- Độ tin cậy:", confidence)

# Hiển thị ảnh
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title(f"Dự đoán: {labels[class_index]}")
plt.axis("off")
plt.show()

import gradio as gr
import numpy as np
from PIL import Image
from tensorflow.keras.models import load_model

# Dictionary thông tin tiền
money_info = {
    "000000": "X",
    "000200": "200 đồng",
    "000500": "500 đồng",
    "001000": "1 000 đồng",
    "002000": "2 000 đồng",
    "005000": "5 000 đồng",
    "010000": "10 000 đồng",
    "020000": "20 000 đồng",
    "050000": "50 000 đồng",
    "100000": "100 000 đồng",
    "200000": "200 000 đồng",
    "500000": "500 000 đồng"
}

# Load model CNN đã train
model_path = 'final_model.h5'  # đổi theo đường dẫn model của bạn
model = load_model(model_path)

# Nhãn lớp (key tương ứng với mệnh giá)
labels = ["000200", "000500", "001000", "002000", "005000", "010000", "020000", "050000", "100000", "200000", "500000", "000000"]

# Hàm dự đoán
def predict_currency(img):
    img = img.convert("RGB").resize((128,128))
    x = np.array(img)/255.0
    x = np.expand_dims(x, axis=0)
    preds = model.predict(x)
    class_idx = np.argmax(preds)
    confidence = preds[0][class_idx]
    return money_info.get(labels[class_idx], labels[class_idx]), round(confidence*100, 2)

# Hàm reset ảnh
def reset_image():
    return None, "", ""

# CSS nâng cao: font, màu nền, icon, bo góc
css_style = """
body {
    background: linear-gradient(to right, #c7f0c7, #fff7d6);
    font-family: 'Poppins', sans-serif;
}
h1 {
    color: #056608;
    font-family: 'Orbitron', sans-serif;
    font-size: 36px;
}
#predict-btn, #reset-btn {
    background-color: #ffd700;
    color: #000;
    font-weight: bold;
    font-size: 18px;
}
.gr-button {border-radius: 15px; padding: 10px 20px;}
.gr-box {
    border: 2px solid #056608;
    border-radius: 15px;
    padding: 15px;
    background-color: rgba(240, 255, 240, 0.9);
}
#label_output .gr-label::before {content: '💰 ';}
#confidence_output .gr-label::before {content: '✅ ';}
"""

# Giao diện Gradio nâng cấp
with gr.Blocks(css=css_style) as demo:
    gr.Markdown("<h1 style='text-align:center;'>Ứng dụng nhận diện tiền Việt Nam 💵💰</h1>")

    with gr.Row():
        with gr.Column():
            img_input = gr.Image(type="pil", label="Chọn ảnh hoặc kéo thả vào đây")
            btn_predict = gr.Button("Nhận diện 🪙", elem_id="predict-btn")
            btn_reset = gr.Button("Chọn ảnh khác 🔄", elem_id="reset-btn")
        with gr.Column():
            label_output = gr.Textbox(label="Loại tiền dự đoán", interactive=False)
            confidence_output = gr.Textbox(label="Độ chính xác (%)", interactive=False)

    # Nút dự đoán
    btn_predict.click(predict_currency, inputs=img_input, outputs=[label_output, confidence_output])
    # Nút reset ảnh và xóa kết quả
    btn_reset.click(reset_image, inputs=None, outputs=[img_input, label_output, confidence_output])

# Chạy app trực tiếp trên Colab
demo.launch(share=True)